//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Riafco.Dataflex.Pro.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActivityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.Riafco.Dataflex.Pro.GlobalResources.ActivityResources", typeof(ActivityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description : .
        /// </summary>
        public static string DisplayActivityDescription {
            get {
                return ResourceManager.GetString("DisplayActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon de l&apos;activité : .
        /// </summary>
        public static string DisplayActivityIcon {
            get {
                return ResourceManager.GetString("DisplayActivityIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image de l&apos;activité : .
        /// </summary>
        public static string DisplayActivityImage {
            get {
                return ResourceManager.GetString("DisplayActivityImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction : .
        /// </summary>
        public static string DisplayActivityIntroduction {
            get {
                return ResourceManager.GetString("DisplayActivityIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre : .
        /// </summary>
        public static string DisplayActivityTitle {
            get {
                return ResourceManager.GetString("DisplayActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredActivityDescription {
            get {
                return ResourceManager.GetString("RequiredActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredActivityIcon {
            get {
                return ResourceManager.GetString("RequiredActivityIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredActivityImage {
            get {
                return ResourceManager.GetString("RequiredActivityImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredActivityIntroduction {
            get {
                return ResourceManager.GetString("RequiredActivityIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredActivityTitle {
            get {
                return ResourceManager.GetString("RequiredActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs obligatoire n&apos;est pas saisie..
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
    }
}
