//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Riafco.Dataflex.Pro.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CountryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.Riafco.Dataflex.Pro.GlobalResources.CountryResources", typeof(CountryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordonnées : .
        /// </summary>
        public static string DisplayCountryCode {
            get {
                return ResourceManager.GetString("DisplayCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description : .
        /// </summary>
        public static string DisplayCountryDescription {
            get {
                return ResourceManager.GetString("DisplayCountryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image du pays : .
        /// </summary>
        public static string DisplayCountryImage {
            get {
                return ResourceManager.GetString("DisplayCountryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom IFCL :.
        /// </summary>
        public static string DisplayCountryName {
            get {
                return ResourceManager.GetString("DisplayCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résumé : .
        /// </summary>
        public static string DisplayCountrySummary {
            get {
                return ResourceManager.GetString("DisplayCountrySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre : .
        /// </summary>
        public static string DisplayCountryTitle {
            get {
                return ResourceManager.GetString("DisplayCountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critéres :.
        /// </summary>
        public static string DisplaySheetTitle {
            get {
                return ResourceManager.GetString("DisplaySheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations :.
        /// </summary>
        public static string DisplaySheetValue {
            get {
                return ResourceManager.GetString("DisplaySheetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredCountryCode {
            get {
                return ResourceManager.GetString("RequiredCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredCountryDescription {
            get {
                return ResourceManager.GetString("RequiredCountryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Pays obligatoire..
        /// </summary>
        public static string RequiredCountryId {
            get {
                return ResourceManager.GetString("RequiredCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredCountryImage {
            get {
                return ResourceManager.GetString("RequiredCountryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredCountryName {
            get {
                return ResourceManager.GetString("RequiredCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredCountrySummary {
            get {
                return ResourceManager.GetString("RequiredCountrySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredCountryTitle {
            get {
                return ResourceManager.GetString("RequiredCountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs obligatoire n&apos;est pas saisie..
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Langue Obligatoire..
        /// </summary>
        public static string RequiredLanguageId {
            get {
                return ResourceManager.GetString("RequiredLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Obligatoire..
        /// </summary>
        public static string RequiredSheetId {
            get {
                return ResourceManager.GetString("RequiredSheetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre Obligatoire..
        /// </summary>
        public static string RequiredSheetTitle {
            get {
                return ResourceManager.GetString("RequiredSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur Obligatoire..
        /// </summary>
        public static string RequiredSheetValue {
            get {
                return ResourceManager.GetString("RequiredSheetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredShortName {
            get {
                return ResourceManager.GetString("RequiredShortName", resourceCulture);
            }
        }
    }
}
