//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Riafco.Dataflex.Pro.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OccurrenceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OccurrenceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.Riafco.Dataflex.Pro.GlobalResources.OccurrenceResources", typeof(OccurrenceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description  : .
        /// </summary>
        public static string DisplayOccurrenceDescription {
            get {
                return ResourceManager.GetString("DisplayOccurrenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin: .
        /// </summary>
        public static string DisplayOccurrenceEndDate {
            get {
                return ResourceManager.GetString("DisplayOccurrenceEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien de l&apos;evenement: .
        /// </summary>
        public static string DisplayOccurrenceLink {
            get {
                return ResourceManager.GetString("DisplayOccurrenceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de début : .
        /// </summary>
        public static string DisplayOccurrenceStartDate {
            get {
                return ResourceManager.GetString("DisplayOccurrenceStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre : .
        /// </summary>
        public static string DisplayOccurrenceTitle {
            get {
                return ResourceManager.GetString("DisplayOccurrenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date invalide..
        /// </summary>
        public static string InvalideDate {
            get {
                return ResourceManager.GetString("InvalideDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déscription ne doit pas dépasser  150 caractéres..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs obligatoire n&apos;est pas saisie..
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredOccurrenceDate {
            get {
                return ResourceManager.GetString("RequiredOccurrenceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredOccurrenceDescription {
            get {
                return ResourceManager.GetString("RequiredOccurrenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredOccurrenceLink {
            get {
                return ResourceManager.GetString("RequiredOccurrenceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredOccurrenceTitle {
            get {
                return ResourceManager.GetString("RequiredOccurrenceTitle", resourceCulture);
            }
        }
    }
}
