//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Riafco.Dataflex.Pro.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PartnerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartnerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.Riafco.Dataflex.Pro.GlobalResources.PartnerResources", typeof(PartnerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo : .
        /// </summary>
        public static string DisplayPartnerImage {
            get {
                return ResourceManager.GetString("DisplayPartnerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien : .
        /// </summary>
        public static string DisplayPartnerLink {
            get {
                return ResourceManager.GetString("DisplayPartnerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom :.
        /// </summary>
        public static string DisplayPartnerName {
            get {
                return ResourceManager.GetString("DisplayPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position :.
        /// </summary>
        public static string DisplayPartnerPosition {
            get {
                return ResourceManager.GetString("DisplayPartnerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position :.
        /// </summary>
        public static string PositionText {
            get {
                return ResourceManager.GetString("PositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs obligatoire n&apos;est pas saisie..
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Obligatoire..
        /// </summary>
        public static string RequiredId {
            get {
                return ResourceManager.GetString("RequiredId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredPartnerImage {
            get {
                return ResourceManager.GetString("RequiredPartnerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredPartnerLink {
            get {
                return ResourceManager.GetString("RequiredPartnerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredPartnerName {
            get {
                return ResourceManager.GetString("RequiredPartnerName", resourceCulture);
            }
        }
    }
}
