//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Riafco.Dataflex.Pro.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PublicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.Riafco.Dataflex.Pro.GlobalResources.PublicationResources", typeof(PublicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La zone goegraphique : .
        /// </summary>
        public static string DisplayArea {
            get {
                return ResourceManager.GetString("DisplayArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;auteur : .
        /// </summary>
        public static string DisplayAuthor {
            get {
                return ResourceManager.GetString("DisplayAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image : .
        /// </summary>
        public static string DisplayImage {
            get {
                return ResourceManager.GetString("DisplayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date : .
        /// </summary>
        public static string DisplayPublicationDate {
            get {
                return ResourceManager.GetString("DisplayPublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier : .
        /// </summary>
        public static string DisplayPublicationFile {
            get {
                return ResourceManager.GetString("DisplayPublicationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résumé : .
        /// </summary>
        public static string DisplayPublicationSummary {
            get {
                return ResourceManager.GetString("DisplayPublicationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre :.
        /// </summary>
        public static string DisplayPublicationTitle {
            get {
                return ResourceManager.GetString("DisplayPublicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de theme : .
        /// </summary>
        public static string DisplayThemeName {
            get {
                return ResourceManager.GetString("DisplayThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opération valide..
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs obligatoire non remplis..
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de theme est obligatoire..
        /// </summary>
        public static string RequiredId {
            get {
                return ResourceManager.GetString("RequiredId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de la langue est obligatoire..
        /// </summary>
        public static string RequiredLanguageId {
            get {
                return ResourceManager.GetString("RequiredLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone est obligatoire..
        /// </summary>
        public static string RequiredPublicationArea {
            get {
                return ResourceManager.GetString("RequiredPublicationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;auteur est obligatoire..
        /// </summary>
        public static string RequiredPublicationAuthor {
            get {
                return ResourceManager.GetString("RequiredPublicationAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date est obligatoire..
        /// </summary>
        public static string RequiredPublicationDate {
            get {
                return ResourceManager.GetString("RequiredPublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatoire..
        /// </summary>
        public static string RequiredPublicationFile {
            get {
                return ResourceManager.GetString("RequiredPublicationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication est obligatoire..
        /// </summary>
        public static string RequiredPublicationId {
            get {
                return ResourceManager.GetString("RequiredPublicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résumé est obligatoire..
        /// </summary>
        public static string RequiredPublicationSummary {
            get {
                return ResourceManager.GetString("RequiredPublicationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre est obligatoire..
        /// </summary>
        public static string RequiredPublicationTitle {
            get {
                return ResourceManager.GetString("RequiredPublicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de theme est obligatoire..
        /// </summary>
        public static string RequiredThemeName {
            get {
                return ResourceManager.GetString("RequiredThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id traduction est obligatoire..
        /// </summary>
        public static string RequiredTranslationId {
            get {
                return ResourceManager.GetString("RequiredTranslationId", resourceCulture);
            }
        }
    }
}
