//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Riafco.Dataflex.Pro.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SectionFileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SectionFileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.Riafco.Dataflex.Pro.GlobalResources.SectionFileResources", typeof(SectionFileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier  : .
        /// </summary>
        public static string DisplaySectionFileSource {
            get {
                return ResourceManager.GetString("DisplaySectionFileSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre : .
        /// </summary>
        public static string DisplaySectionFileText {
            get {
                return ResourceManager.GetString("DisplaySectionFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de fichier est obligatoire..
        /// </summary>
        public static string RequiredFileSectionId {
            get {
                return ResourceManager.GetString("RequiredFileSectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id langue est pbligatoire..
        /// </summary>
        public static string RequiredLanguageId {
            get {
                return ResourceManager.GetString("RequiredLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de fichier est obligatoire..
        /// </summary>
        public static string RequiredSectionFileId {
            get {
                return ResourceManager.GetString("RequiredSectionFileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier est obliagtoire..
        /// </summary>
        public static string RequiredSectionFileSource {
            get {
                return ResourceManager.GetString("RequiredSectionFileSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre du fichier est obligatoire..
        /// </summary>
        public static string RequiredSectionFileText {
            get {
                return ResourceManager.GetString("RequiredSectionFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de la section est obligatoire..
        /// </summary>
        public static string RequiredSectionId {
            get {
                return ResourceManager.GetString("RequiredSectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id traduction est obligatoire..
        /// </summary>
        public static string RequiredTranslationId {
            get {
                return ResourceManager.GetString("RequiredTranslationId", resourceCulture);
            }
        }
    }
}
