//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riafco.Dataflex.Pro.GlobalResources.Publications {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PublicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riafco.Dataflex.Pro.GlobalResources.Publications.PublicationResources", typeof(PublicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Géographique : .
        /// </summary>
        public static string DisplayArea {
            get {
                return ResourceManager.GetString("DisplayArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur : .
        /// </summary>
        public static string DisplayAuthor {
            get {
                return ResourceManager.GetString("DisplayAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date : .
        /// </summary>
        public static string DisplayDate {
            get {
                return ResourceManager.GetString("DisplayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème : .
        /// </summary>
        public static string DisplayTheme {
            get {
                return ResourceManager.GetString("DisplayTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valider.
        /// </summary>
        public static string FilterBtn {
            get {
                return ResourceManager.GetString("FilterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filtres.
        /// </summary>
        public static string FiltreTitle {
            get {
                return ResourceManager.GetString("FiltreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre une description globale sur la page ressources de riafco..
        /// </summary>
        public static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos ressources.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lire plus.
        /// </summary>
        public static string ReadMoreBtn {
            get {
                return ResourceManager.GetString("ReadMoreBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ obligatoire..
        /// </summary>
        public static string RequiredId {
            get {
                return ResourceManager.GetString("RequiredId", resourceCulture);
            }
        }
    }
}
